version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - zabbix
    ports:
      - '3306:3306'
    volumes:
      - BD_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=admin
  
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - zabbix
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=admin
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - zabbix
    restart: always
    ports:
      - '8010:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=admin
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.0-latest
    container_name: zabbix_agent
    networks: 
      - zabbix
    ports:
      - "10049:10049"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"    

volumes:
 BD_mysql:
    

networks:
  zabbix:
   

          
          
 
